### ISSUE TITLE
File picker option

### ISSUE THREAD

**Issue by dxcore35** [danielo515/obsidian-modal-form#241]
# FEATURE DESCRIPTION

Create new option here:

![Screenshot 2024-04-24 at 16 45 49](https://github.com/danielo515/obsidian-modal-form/assets/7279156/25f1b640-f7e2-4ee6-97d3-3bf3e23c3878)

It will open file picker:

![image](https://github.com/danielo515/obsidian-modal-form/assets/7279156/259733df-d50a-4f5d-95e3-ef3e093d7082)

It can return object or it can just return full path of this file for another use in javascript.

# EXAMPLE USE CASE

I have modal to create new project and I would like to set the image cover for this. The modal will return me the full path of file I select with this new feature. And in javascript I will copy this file into project folder and change his name.

**Comment by josephgarnier** [comment]
Until this functionality is implemented, **here's a temporary solution** for those who want it.

1. In your form, create a field of type `Dataview`.
2. In the code field, paste this:

```js
(async () => {
  if (!globalThis.selectedDirectory || globalThis.selectedDirectory === "") {
    const dirHandle = await self.showDirectoryPicker({ mode: "read" });
    if (!dirHandle) {
      return [""];
    }
    globalThis.selectedDirectory = dirHandle.name;
  }
  return [globalThis.selectedDirectory];
})();
```
3. In your markdown file, before calling the form, place the instruction `globalThis.selectedDirectory = ‘’;`. For example:

```js
globalThis.selectedDirectory = "";
const modalForm = app.plugins.plugins.modalforms.api;
const result = await modalForm.openForm(my-form");

const selected = result.get("my-selected-dir-field");
```

**Explanation:** As the ModalForm plugin executes the contents of the field in a loop, the `selectedDirectory` global variable ensures that the file picker is only called once, when the form is called. Otherwise, the plugin will spam indefinitely with the file picker.

**Comment by danielo515** [comment]
I recently realized this feature can be understood as a way to pick files that already exist in the vault (like, attached images, or PDFs). I'm not sure how to name each of those to have a clear differentiation between the two, because I see value in the two.
I am also not sure about the implementation details of this one.
Should modal form take care of saving the file? Or should it be returned as a file-blob and let you do whatever you want? Maybe with one or two helper methods?

**Comment by dxcore35** [comment]
In my case I want to import external file (out of Vault) into vault to specific location.

**Comment by josephgarnier** [comment]
Same as @dxcore35  (the temporary code I posted above allows you to do this).
