### ISSUE TITLE
Add Discussion Tab to Github Page

### ISSUE THREAD

**Issue by motion2082** [danielo515/obsidian-modal-form#346]
**Is your feature request related to a problem? Please describe.**

add discussion tab to github page so dont have to log issues for discussions

**Describe the solution you'd like**

Discussion tab like the Meta Bind Github

**Additional context**

**Comment by danielo515** [comment]
I thought about it several times.
I started this plugin as something small and simple, so at first I thought it was not worth it.
Also, because this plugin is also so easy to integrate with other plugins I was not sure if it was better to just mention modal forms on other plugins discussions as an addon to that plugi.
Finally, there was also the obsidian community forums, which are a great place for having discussions about any plugin.
That said, it is true there have been several issues that were just questions, and that probably have been better solved as discussions, so I will enable it and see where that leads us to.
